version: 2.1
jobs:
  cycle:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run
          command: npm start

workflows:
  version: 2.1
  scheduled:
    jobs:
      - cycle
    triggers:
      - schedule:
          cron: "0 20 * * 1-5"
          filters:
            branches:
              only:
                - master
